"use client";

import { useEffect, useState } from "react";

type Reflection = {
  id: number;
  agent_name: string;
  reflection_type: string;
  wins: string[];
  concerns: string[];
  recommendation: string;
  summary: string;
  confidence_score: number;
  created_at: string;
};

export default function AgentReflectionsPage() {
  const [reflections, setReflections] = useState<Reflection[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReflections();
  }, []);

  const loadReflections = async () => {
    try {
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/api/agent-reflections/`
      );

      const data = await res.json();

      setReflections(data);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const getTheme = (agent: string) => {
    if (agent.includes("Career")) {
      return {
        icon: "💼",
        border: "border-blue-500/30",
        bg: "bg-blue-500/5",
        text: "text-blue-300",
      };
    }

    if (agent.includes("Finance")) {
      return {
        icon: "💰",
        border: "border-green-500/30",
        bg: "bg-green-500/5",
        text: "text-green-300",
      };
    }

    if (agent.includes("Health")) {
      return {
        icon: "❤️",
        border: "border-pink-500/30",
        bg: "bg-pink-500/5",
        text: "text-pink-300",
      };
    }

    return {
      icon: "📚",
      border: "border-violet-500/30",
      bg: "bg-violet-500/5",
      text: "text-violet-300",
    };
  };

  return (
    <main className="min-h-screen bg-slate-950 p-8 text-white">
      <div className="mx-auto max-w-7xl">

        <p className="text-sm text-cyan-300">
          Digital Twin Intelligence
        </p>

        <h1 className="mt-2 text-4xl font-bold">
          Agent Reflections
        </h1>

        <p className="mt-3 text-slate-400 max-w-3xl">
          Weekly self-reflections generated by your Digital Twin agents.
        </p>

        {loading ? (
          <div className="mt-8 rounded-2xl bg-slate-900 p-8">
            Loading reflections...
          </div>
        ) : (
          <div className="mt-8 grid gap-6 lg:grid-cols-2">
            {reflections.map((reflection) => {
              const theme = getTheme(reflection.agent_name);

              return (
                <div
                  key={reflection.id}
                  className={`rounded-2xl border ${theme.border} ${theme.bg} p-6`}
                >
                  <div className="flex items-center justify-between">

                    <div>
                      <div className="text-3xl">
                        {theme.icon}
                      </div>

                      <h2 className="mt-3 text-2xl font-bold">
                        {reflection.agent_name}
                      </h2>
                    </div>

                    <div>
                      <div className="rounded-xl bg-slate-900 px-4 py-3 text-center">
                        <p className="text-xs text-slate-400">
                          Confidence
                        </p>

                        <h3
                          className={`text-3xl font-bold ${theme.text}`}
                        >
                          {reflection.confidence_score}%
                        </h3>
                      </div>
                    </div>
                  </div>

                  <p className="mt-5 text-sm leading-7 text-slate-300">
                    {reflection.summary}
                  </p>

                  <div className="mt-5">
                    <p className={`text-sm font-medium ${theme.text}`}>
                      Wins
                    </p>

                    <ul className="mt-3 space-y-2 text-sm text-slate-300">
                      {reflection.wins.map((item, index) => (
                        <li key={index}>✅ {item}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="mt-5">
                    <p className="text-sm font-medium text-yellow-300">
                      Concerns
                    </p>

                    <ul className="mt-3 space-y-2 text-sm text-slate-300">
                      {reflection.concerns.map((item, index) => (
                        <li key={index}>⚠️ {item}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="mt-5">
                    <p className="text-sm font-medium text-cyan-300">
                      Recommendation
                    </p>

                    <div className="mt-3 rounded-xl bg-slate-900 p-4 text-sm leading-6 text-slate-300">
                      {reflection.recommendation}
                    </div>
                  </div>

                  <p className="mt-5 text-xs text-slate-500">
                    {new Date(
                      reflection.created_at
                    ).toLocaleString()}
                  </p>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </main>
  );
}