"use client";

import { apiFetch } from "@/lib/api";

import AppShell from "@/components/AppShell";
import { useEffect, useMemo, useState } from "react";

type JournalEntry = {
  type: string;
  agent: string;
  title: string;
  date: string;
};

export default function TwinJournalPage() {
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [agentFilter, setAgentFilter] = useState("All");
  const [typeFilter, setTypeFilter] = useState("All");

  useEffect(() => {
    loadJournal();
  }, []);

  const loadJournal = async () => {
    try {
      const res = await apiFetch(
        `${process.env.NEXT_PUBLIC_API_URL}/api/twin-journal/`
      );
      const data = await res.json();
      setEntries(data);
    } catch (error) {
      console.error("Twin Journal error:", error);
    } finally {
      setLoading(false);
    }
  };

  const filteredEntries = useMemo(() => {
    return entries.filter((entry) => {
      const matchesAgent =
        agentFilter === "All" || entry.agent.includes(agentFilter);

      const matchesType =
        typeFilter === "All" || entry.type === typeFilter.toLowerCase();

      return matchesAgent && matchesType;
    });
  }, [entries, agentFilter, typeFilter]);

  const memoryCount = entries.filter((e) => e.type === "memory").length;
  const reflectionCount = entries.filter((e) => e.type === "reflection").length;

  return (
    <AppShell>
      <div>
        <p className="text-sm text-cyan-300">Digital Twin Intelligence</p>

        <h1 className="mt-2 text-3xl font-bold sm:text-4xl">Twin Journal</h1>

        <p className="mt-3 max-w-3xl text-slate-400">
          A timeline of memories, reflections, learning moments, and insights
          generated by your Digital Twin agents.
        </p>

        <section className="mt-8 grid grid-cols-2 gap-4 lg:grid-cols-4">
          <StatCard label="Total Entries" value={entries.length} />
          <StatCard label="Memories" value={memoryCount} />
          <StatCard label="Reflections" value={reflectionCount} />
          <StatCard label="Visible Entries" value={filteredEntries.length} />
        </section>

        <section className="mt-8 rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-5 sm:p-6">
          <p className="text-sm text-cyan-300">Growth Summary</p>
          <h2 className="mt-2 text-2xl font-bold">
            Your Digital Twin is building a personal history.
          </h2>
          <p className="mt-3 text-sm leading-6 text-slate-300">
            Your system has stored {memoryCount} memories and generated{" "}
            {reflectionCount} reflections. As this grows, the agents will become
            better at understanding your goals, risks, habits, and progress.
          </p>
        </section>

        <section className="mt-8 flex flex-wrap gap-3">
          {["All", "Career", "Finance", "Health", "Learning"].map((agent) => (
            <button
              key={agent}
              onClick={() => setAgentFilter(agent)}
              className={`rounded-full px-4 py-2 text-sm ${
                agentFilter === agent
                  ? "bg-cyan-500 text-white"
                  : "bg-slate-800 text-slate-300 hover:bg-slate-700"
              }`}
            >
              {agent}
            </button>
          ))}

          <div className="mx-2 hidden h-9 w-px bg-slate-700 md:block" />

          {["All", "Memory", "Reflection"].map((type) => (
            <button
              key={type}
              onClick={() => setTypeFilter(type)}
              className={`rounded-full px-4 py-2 text-sm ${
                typeFilter === type
                  ? "bg-violet-500 text-white"
                  : "bg-slate-800 text-slate-300 hover:bg-slate-700"
              }`}
            >
              {type}
            </button>
          ))}
        </section>

        {loading ? (
          <div className="mt-8 rounded-2xl bg-slate-900 p-8">
            Loading journal...
          </div>
        ) : (
          <div className="relative mt-10">
            <div className="absolute left-5 top-0 h-full w-1 rounded-full bg-slate-700 sm:left-6" />

            <div className="space-y-6">
              {filteredEntries.map((entry, index) => {
                const theme = getTheme(entry.agent);

                return (
                  <div key={index} className="relative ml-10 sm:ml-12">
                    <div
                      className={`absolute -left-10 flex h-10 w-10 items-center justify-center rounded-full border-4 bg-slate-950 sm:-left-12 sm:h-12 sm:w-12 ${theme.color}`}
                    >
                      <span className="text-xl">{theme.icon}</span>
                    </div>

                    <div className="rounded-2xl border border-slate-700 bg-slate-900 p-4 sm:p-6">
                      <div className="flex flex-wrap items-center justify-between gap-3">
                        <div>
                          <p className={`text-sm font-medium ${theme.text}`}>
                            {entry.agent}
                          </p>

                          <div className="mt-2 flex items-center gap-2">
                            <span className="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-300">
                              {entry.type === "reflection"
                                ? "📝 Reflection"
                                : "🧠 Memory"}
                            </span>
                          </div>
                        </div>

                        <span className="text-xs text-slate-500">
                          {new Date(entry.date).toLocaleString()}
                        </span>
                      </div>

                      <p className="mt-4 leading-7 text-slate-300">
                        {entry.title}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>

            {filteredEntries.length === 0 && (
              <div className="rounded-2xl bg-slate-900 p-8 text-center text-slate-400">
                No journal entries found for this filter.
              </div>
            )}
          </div>
        )}
      </div>
    </AppShell>
  );
}

function StatCard({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-2xl bg-slate-900 p-5">
      <p className="text-sm text-slate-400">{label}</p>
      <h2 className="mt-2 text-3xl font-bold text-cyan-400">{value}</h2>
    </div>
  );
}

function getTheme(agent: string) {
  if (agent.includes("Career")) {
    return { icon: "💼", color: "border-blue-500", text: "text-blue-300" };
  }

  if (agent.includes("Finance")) {
    return { icon: "💰", color: "border-green-500", text: "text-green-300" };
  }

  if (agent.includes("Health")) {
    return { icon: "❤️", color: "border-pink-500", text: "text-pink-300" };
  }

  return { icon: "📚", color: "border-violet-500", text: "text-violet-300" };
}